guard 'mozrepl' do
  watch(%r{app/.+\.(erb|haml)})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  watch(%r{config/locales/.+\.yml})
end

### or with options...
# guard 'mozrepl', :host => 'localhost', :port => 4242, :verbose => true do
#   ...
